package com.agon.app.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.agon.app.data.SubtitleMethod

@Entity(tableName = "subtitles")
data class SubtitleEntity(
    @PrimaryKey
    val id: String,
    val downloadId: String,
    val language: String,
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val method: SubtitleMethod,
    val filePath: String,
    val fileSize: Long,
    val createdAt: Long = System.currentTimeMillis()
)
