package com.agon.app.data

import kotlinx.serialization.Serializable

@Serializable
enum class DownloadStatus {
    QUEUED,
    ANALYZING,
    DOWNLOADING,
    PAUSED,
    EXTRACTING_SUBS,
    TRANSLATING,
    COMPLETED,
    FAILED,
    CANCELLED
}

@Serializable
enum class SubtitleMethod {
    DIRECT_AR,
    TRANSLATED_FROM_OTHER,
    WHISPER_GENERATED,
    NONE
}

@Serializable
enum class DownloadMode {
    VIDEO_AND_SUBTITLE,  // Mode 1: Download video + subs (translate if needed)
    VIDEO_ONLY,          // Mode 2: Download video only, no subs
    SUBTITLE_ONLY        // Mode 3: Download subs only, no video
}

@Serializable
data class VideoQuality(
    val id: String,
    val label: String,
    val resolution: String,
    val fileSize: String,
    val format: String
)

@Serializable
data class SubtitleInfo(
    val language: String,
    val languageCode: String,
    val isAutoGenerated: Boolean
)

@Serializable
data class VideoInfo(
    val title: String,
    val thumbnailUrl: String,
    val duration: String,
    val uploader: String,
    val qualities: List<VideoQuality>,
    val availableSubtitles: List<SubtitleInfo>,
    val sourceUrl: String
)

@Serializable
data class DownloadItem(
    val id: String = "",
    val url: String = "",
    val title: String = "",
    val thumbnailUrl: String = "",
    val selectedQuality: String = "",
    val downloadMode: DownloadMode = DownloadMode.VIDEO_AND_SUBTITLE,
    val subtitleMethod: SubtitleMethod = SubtitleMethod.NONE,
    val status: DownloadStatus = DownloadStatus.QUEUED,
    val progress: Int = 0,
    val totalSize: String = "",
    val downloadedSize: String = "",
    val downloadSpeed: String = "",
    val eta: String = "",
    val srtFilePath: String = "",
    val videoFilePath: String = "",
    val errorMessage: String = "",
    val timestamp: Long = System.currentTimeMillis(),
    val isPaused: Boolean = false,
    val workManagerId: String = ""
)

@Serializable
data class AiModel(
    val id: String,
    val name: String,
    val type: String,
    val version: String,
    val sizeBytes: Long,
    val sizeFormatted: String,
    val filePath: String,
    val checksum: String,
    val isDownloaded: Boolean,
    val isCorrupted: Boolean,
    val downloadUrl: String,
    val description: String,
    val language: String?,
    val isPaused: Boolean = false,       // تمت الإضافة: لتتبع حالة الإيقاف المؤقت
    val downloadedBytes: Long = 0L,      // تمت الإضافة: لتتبع حجم ما تم تحميله للاستئناف
    val createdAt: Long = System.currentTimeMillis(),
    val lastUsedAt: Long? = null
)

@Serializable
data class WhisperModel(
    val id: String,
    val name: String,
    val size: String,
    val sizeBytes: Long,
    val isDownloaded: Boolean = false,
    val isDownloading: Boolean = false,
    val downloadProgress: Int = 0,
    val description: String
)

@Serializable
data class EngineInfo(
    val name: String,
    val version: String,
    val isInstalled: Boolean,
    val isChecking: Boolean = false,
    val hasUpdate: Boolean = false,
    val latestVersion: String = ""
)
