package com.agon.app.domain.usecase

import com.agon.app.data.SubtitleInfo
import com.agon.app.data.SubtitleMethod
import com.agon.app.data.VideoInfo
import com.agon.app.data.VideoQuality
import com.agon.app.engine.YtDlpEngine
import com.agon.app.engine.YtDlpVideoInfo
import javax.inject.Inject

class AnalyzeUrlUseCase @Inject constructor(
    private val ytDlpEngine: YtDlpEngine
) {
    suspend operator fun invoke(url: String): Result<VideoInfo> {
        return ytDlpEngine.analyzeUrl(url).map { ytDlpInfo ->
            ytDlpInfo.toVideoInfo(url)
        }
    }

    private fun YtDlpVideoInfo.toVideoInfo(sourceUrl: String): VideoInfo {
        val qualities = extractQualities()
        val subtitles = extractSubtitles()
        val durationStr = formatDuration(duration)

        return VideoInfo(
            title = title,
            thumbnailUrl = thumbnail ?: "",
            duration = durationStr,
            uploader = uploader,
            qualities = qualities,
            availableSubtitles = subtitles,
            sourceUrl = sourceUrl
        )
    }

    private fun YtDlpVideoInfo.extractQualities(): List<VideoQuality> {
        val qualityMap = mutableMapOf<String, VideoQuality>()

        formats.forEach { format ->
            val height = format.height ?: return@forEach
            val width = format.width ?: return@forEach

            val resolution = "${width}×${height}"
            val label = when {
                height >= 2160 -> "2160p (4K)"
                height >= 1440 -> "1440p (2K)"
                height >= 1080 -> "1080p (Full HD)"
                height >= 720 -> "720p (HD)"
                height >= 480 -> "480p"
                height >= 360 -> "360p"
                else -> "${height}p"
            }

            val fileSize = format.filesize ?: format.filesize_approx
            val fileSizeStr = if (fileSize != null) formatFileSize(fileSize) else "Unknown"

            val quality = VideoQuality(
                id = format.format_id,
                label = label,
                resolution = resolution,
                fileSize = fileSizeStr,
                format = format.ext
            )

            qualityMap[height.toString()] = quality
        }

        return qualityMap.values.sortedByDescending {
            it.resolution.split("×").firstOrNull()?.toIntOrNull() ?: 0
        }
    }

    private fun YtDlpVideoInfo.extractSubtitles(): List<SubtitleInfo> {
        val subtitleList = mutableListOf<SubtitleInfo>()

        subtitles.forEach { (langCode, subs) ->
            val langName = getLanguageName(langCode)
            subtitleList.add(
                SubtitleInfo(
                    language = langName,
                    languageCode = langCode,
                    isAutoGenerated = false
                )
            )
        }

        automatic_captions.forEach { (langCode, subs) ->
            if (!subtitles.containsKey(langCode)) {
                val langName = getLanguageName(langCode)
                subtitleList.add(
                    SubtitleInfo(
                        language = "$langName (Auto)",
                        languageCode = langCode,
                        isAutoGenerated = true
                    )
                )
            }
        }

        return subtitleList
    }

    private fun getLanguageName(code: String): String {
        return when (code.lowercase()) {
            "ar" -> "العربية"
            "en" -> "English"
            "es" -> "Español"
            "fr" -> "Français"
            "de" -> "Deutsch"
            "it" -> "Italiano"
            "pt" -> "Português"
            "ru" -> "Русский"
            "zh" -> "中文"
            "ja" -> "日本語"
            "ko" -> "한국어"
            "tr" -> "Türkçe"
            "hi" -> "हिन्दी"
            "nl" -> "Nederlands"
            "pl" -> "Polski"
            "sv" -> "Svenska"
            else -> code.uppercase()
        }
    }

    private fun formatDuration(seconds: Int?): String {
        if (seconds == null) return "Unknown"
        val hours = seconds / 3600
        val minutes = (seconds % 3600) / 60
        val secs = seconds % 60
        return if (hours > 0) {
            String.format("%d:%02d:%02d", hours, minutes, secs)
        } else {
            String.format("%d:%02d", minutes, secs)
        }
    }

    private fun formatFileSize(bytes: Long): String {
        return when {
            bytes >= 1_073_741_824 -> String.format("~%.1f GB", bytes / 1_073_741_824.0)
            bytes >= 1_048_576 -> String.format("~%.1f MB", bytes / 1_048_576.0)
            bytes >= 1024 -> String.format("~%.1f KB", bytes / 1024.0)
            else -> "$bytes B"
        }
    }
}
