package com.agon.app.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class DownloadItemTest {

    @Test
    fun `DownloadItem default values are correct`() {
        val item = DownloadItem()

        assertEquals("", item.id)
        assertEquals("", item.url)
        assertEquals("", item.title)
        assertEquals("", item.thumbnailUrl)
        assertEquals("", item.selectedQuality)
        assertEquals(DownloadMode.VIDEO_AND_SUBTITLE, item.downloadMode)
        assertEquals(SubtitleMethod.NONE, item.subtitleMethod)
        assertEquals(DownloadStatus.QUEUED, item.status)
        assertEquals(0, item.progress)
        assertEquals("", item.totalSize)
        assertEquals("", item.downloadedSize)
        assertEquals("", item.downloadSpeed)
        assertEquals("", item.eta)
        assertEquals("", item.srtFilePath)
        assertEquals("", item.videoFilePath)
        assertEquals("", item.errorMessage)
        assertFalse(item.isPaused)
        assertEquals("", item.workManagerId)
    }

    @Test
    fun `DownloadStatus enum has all expected values`() {
        val statuses = DownloadStatus.entries
        assertEquals(9, statuses.size)
        assertTrue(statuses.contains(DownloadStatus.QUEUED))
        assertTrue(statuses.contains(DownloadStatus.ANALYZING))
        assertTrue(statuses.contains(DownloadStatus.DOWNLOADING))
        assertTrue(statuses.contains(DownloadStatus.PAUSED))
        assertTrue(statuses.contains(DownloadStatus.EXTRACTING_SUBS))
        assertTrue(statuses.contains(DownloadStatus.TRANSLATING))
        assertTrue(statuses.contains(DownloadStatus.COMPLETED))
        assertTrue(statuses.contains(DownloadStatus.FAILED))
        assertTrue(statuses.contains(DownloadStatus.CANCELLED))
    }

    @Test
    fun `SubtitleMethod enum has all expected values`() {
        val methods = SubtitleMethod.entries
        assertEquals(4, methods.size)
        assertTrue(methods.contains(SubtitleMethod.DIRECT_AR))
        assertTrue(methods.contains(SubtitleMethod.TRANSLATED_FROM_OTHER))
        assertTrue(methods.contains(SubtitleMethod.WHISPER_GENERATED))
        assertTrue(methods.contains(SubtitleMethod.NONE))
    }

    @Test
    fun `DownloadMode enum has all expected values`() {
        val modes = DownloadMode.entries
        assertEquals(3, modes.size)
        assertTrue(modes.contains(DownloadMode.VIDEO_AND_SUBTITLE))
        assertTrue(modes.contains(DownloadMode.VIDEO_ONLY))
        assertTrue(modes.contains(DownloadMode.SUBTITLE_ONLY))
    }

    @Test
    fun `VideoQuality data class holds correct values`() {
        val quality = VideoQuality(
            id = "137",
            label = "1080p (Full HD)",
            resolution = "1920×1080",
            fileSize = "~250 MB",
            format = "mp4"
        )

        assertEquals("137", quality.id)
        assertEquals("1080p (Full HD)", quality.label)
        assertEquals("1920×1080", quality.resolution)
        assertEquals("~250 MB", quality.fileSize)
        assertEquals("mp4", quality.format)
    }

    @Test
    fun `SubtitleInfo data class holds correct values`() {
        val subtitle = SubtitleInfo(
            language = "العربية",
            languageCode = "ar",
            isAutoGenerated = true
        )

        assertEquals("العربية", subtitle.language)
        assertEquals("ar", subtitle.languageCode)
        assertTrue(subtitle.isAutoGenerated)
    }

    @Test
    fun `VideoInfo data class holds correct values`() {
        val qualities = listOf(
            VideoQuality("137", "1080p", "1920×1080", "~250 MB", "mp4"),
            VideoQuality("136", "720p", "1280×720", "~120 MB", "mp4")
        )
        val subtitles = listOf(
            SubtitleInfo("العربية", "ar", false),
            SubtitleInfo("English", "en", false)
        )
        val videoInfo = VideoInfo(
            title = "Test Video",
            thumbnailUrl = "https://example.com/thumb.jpg",
            duration = "10:30",
            uploader = "Test Channel",
            qualities = qualities,
            availableSubtitles = subtitles,
            sourceUrl = "https://example.com/video"
        )

        assertEquals("Test Video", videoInfo.title)
        assertEquals("https://example.com/thumb.jpg", videoInfo.thumbnailUrl)
        assertEquals("10:30", videoInfo.duration)
        assertEquals("Test Channel", videoInfo.uploader)
        assertEquals(2, videoInfo.qualities.size)
        assertEquals(2, videoInfo.availableSubtitles.size)
        assertEquals("https://example.com/video", videoInfo.sourceUrl)
    }

    @Test
    fun `DownloadItem copy updates fields correctly`() {
        val original = DownloadItem(
            id = "test-id",
            title = "Original Title",
            status = DownloadStatus.QUEUED,
            progress = 0
        )

        val updated = original.copy(
            status = DownloadStatus.DOWNLOADING,
            progress = 50,
            downloadedSize = "125 MB"
        )

        assertEquals("test-id", updated.id)
        assertEquals("Original Title", updated.title)
        assertEquals(DownloadStatus.DOWNLOADING, updated.status)
        assertEquals(50, updated.progress)
        assertEquals("125 MB", updated.downloadedSize)
    }

    @Test
    fun `AiModel data class holds correct values`() {
        val model = AiModel(
            id = "whisper-base",
            name = "Whisper Base",
            type = "whisper",
            version = "1.0",
            sizeBytes = 142_000_000L,
            sizeFormatted = "142 MB",
            filePath = "/data/whisper-base.bin",
            checksum = "abc123",
            isDownloaded = true,
            isCorrupted = false,
            downloadUrl = "https://example.com/model.bin",
            description = "Good balance of speed and accuracy",
            language = null
        )

        assertEquals("whisper-base", model.id)
        assertEquals("Whisper Base", model.name)
        assertEquals("whisper", model.type)
        assertTrue(model.isDownloaded)
        assertFalse(model.isCorrupted)
    }

    @Test
    fun `EngineInfo data class holds correct values`() {
        val engine = EngineInfo(
            name = "yt-dlp",
            version = "2024.12.06",
            isInstalled = true,
            isChecking = false,
            hasUpdate = true,
            latestVersion = "2025.01.15"
        )

        assertEquals("yt-dlp", engine.name)
        assertEquals("2024.12.06", engine.version)
        assertTrue(engine.isInstalled)
        assertFalse(engine.isChecking)
        assertTrue(engine.hasUpdate)
        assertEquals("2025.01.15", engine.latestVersion)
    }
}
